% taller-qmd-template.tex — plantilla pandoc/quarto para TALLERES del curso AED
% Basada en el driver de tesis main-es.tex (clase mitthesis parcheada UR), con
% portada y resumen a medida para trabajos de curso. Compilar con XeLaTeX
% (build.sh usa latexmk -pdfxe).
%
%   Metadatos por taller (YAML del .qmd): title, subtitle, fecha, resumen, palabras
%   (fecha: clave propia; quarto reformatea `date:` a ISO-8601)
%   Datos del curso (compartidos):         common/meta-taller-es.tex
%   Preliminares (portada/resumen/índice): common/frontmatter-taller.tex
\def\oaslang{es}
\DocumentMetadata{lang=es, pdfversion=1.7, pdfstandard=a-2b}
% Guardarraíl de motor: fontset=libertinus exige XeLaTeX (ver main-es.tex).
\RequirePackage{iftex}\RequireXeTeX
\documentclass[oneside, openany, fontset=libertinus]{mitthesis}
\input{common/preamble}

% --- Compatibilidad con la salida de pandoc ---
\usepackage{fancyvrb}   % entornos Shaded/Highlighting del código R
\usepackage{upquote}    % comillas rectas en verbatim
\usepackage{float}      % opción de flotante [H] que quarto usa en las figuras
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{241,243,245}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.40,0.45,0.13}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\BuiltInTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\ExtensionTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.28,0.35,0.67}{#1}}
\newcommand{\ImportTok}[1]{\textcolor[rgb]{0.00,0.46,0.62}{#1}}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.07,0.07,0.07}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\providecommand{\tightlist}{\setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\providecommand{\pandocbounded}[1]{#1}

% --- Resolución de recursos hacia la plantilla (layout taller-XX junto a template/) ---
\graphicspath{{assets/pics/}{figures/}{../template/assets/pics/}{../template/figures/}}
\addbibresource{../template/bib/refs-taller.bib}

% --- Metadatos del taller (vienen del YAML del .qmd vía pandoc) ---
\newcommand{\tallertitulo}{Taller 1 --- Exploración de datos
meteorológicos (ORI)}
\newcommand{\tallersubtitulo}{Análisis Estadístico de Datos}
\newcommand{\tallerfecha}{Bogotá D.C., septiembre de 2026}
\newcommand{\tallerresumen}{Exploración descriptiva de la base
meteorológica ORI (IDEAM, región Orinoquía): 4543 registros de 18
variables, de los cuales 118 corresponden a mediciones al mediodía. Se
clasifican las variables por escala y clase, se resumen univariadamente
temperatura y velocidad del viento (posición, dispersión y forma), se
detectan atípicos por el criterio de Tukey en presión y punto de rocío,
y se estudia la asociación bivariada entre temperatura y viento mediante
covarianza y correlación de Pearson. Se cierra con la estimación no
paramétrica de densidades (histograma y kernel) y su comparación con el
modelo normal.}
\newcommand{\tallerpalabras}{estadística descriptiva; boxplot; atípicos
de Tukey; covarianza; correlación; densidad kernel; IDEAM}
\input{common/meta-taller-es}

\begin{document}
\input{common/frontmatter-taller}

\chapter{Los datos}\label{datos}

La base \texttt{ORI.csv} (IDEAM) contiene mediciones meteorológicas de
municipios de la región Orinoquía. Cada observación es la medición de un
municipio a una hora de un día dado; las unidades provienen del
enunciado del taller y de la fuente IDEAM: temperatura en °C, velocidad
del viento en mph, presión en hPa, precipitación en mm/h.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# ORI.csv se autolocaliza: se prueban los lugares habituales en orden.}
\CommentTok{\# La copia del curso viene en ISO{-}8859{-}1 y la de data/ en UTF{-}8: se detecta}
\CommentTok{\# en vez de suponer (suponer rompe las tildes de los municipios).}
\NormalTok{ruta }\OtherTok{\textless{}{-}} \FunctionTok{Filter}\NormalTok{(file.exists, }\FunctionTok{c}\NormalTok{(}\StringTok{"ORI.csv"}\NormalTok{, }\StringTok{"data/ORI.csv"}\NormalTok{,}
                              \StringTok{"../../../data/ORI.csv"}\NormalTok{))[}\DecValTok{1}\NormalTok{]}
\NormalTok{codificacion }\OtherTok{\textless{}{-}} \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{all}\NormalTok{(}\FunctionTok{validUTF8}\NormalTok{(}\FunctionTok{readLines}\NormalTok{(ruta, }\AttributeTok{warn =} \ConstantTok{FALSE}\NormalTok{,}
                                            \AttributeTok{encoding =} \StringTok{"bytes"}\NormalTok{))))}
  \StringTok{"UTF{-}8"} \ControlFlowTok{else} \StringTok{"latin1"}
\NormalTok{datos }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(ruta, }\AttributeTok{sep =} \StringTok{";"}\NormalTok{, }\AttributeTok{dec =} \StringTok{"."}\NormalTok{, }\AttributeTok{fileEncoding =}\NormalTok{ codificacion,}
                  \AttributeTok{stringsAsFactors =} \ConstantTok{FALSE}\NormalTok{)}
\FunctionTok{names}\NormalTok{(datos) }\OtherTok{\textless{}{-}} \FunctionTok{trimws}\NormalTok{(}\FunctionTok{names}\NormalTok{(datos))   }\CommentTok{\# el encabezado trae "Pronostico "}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Al cargar:"}\NormalTok{, }\FunctionTok{nrow}\NormalTok{(datos), }\StringTok{"filas x"}\NormalTok{, }\FunctionTok{ncol}\NormalTok{(datos), }\StringTok{"columnas}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Al cargar: 4543 filas x 18 columnas
\end{verbatim}

Cada fila es una \textbf{unidad estadística}: la entidad sobre la que se
hace una medición completa (un municipio en un momento dado). Las
columnas son las variables medidas.

\chapter{Registros del mediodía}\label{preparacion}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{datos }\OtherTok{\textless{}{-}}\NormalTok{ datos[datos}\SpecialCharTok{$}\NormalTok{Hora }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\StringTok{"12:00"}\NormalTok{), ]}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Registros a medio día (12:00):"}\NormalTok{, }\FunctionTok{nrow}\NormalTok{(datos), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Registros a medio día (12:00): 118 
\end{verbatim}

De las 4543 unidades estadísticas, 118 fueron medidas al mediodía; sobre
ese subconjunto se desarrolla el resto del taller.

\chapter{Frecuencias del pronóstico}\label{p2}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tabla }\OtherTok{\textless{}{-}} \FunctionTok{sort}\NormalTok{(}\FunctionTok{table}\NormalTok{(datos}\SpecialCharTok{$}\NormalTok{Pronostico), }\AttributeTok{decreasing =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{(}\FunctionTok{cbind}\NormalTok{(}\AttributeTok{n =}\NormalTok{ tabla, }\AttributeTok{prop =} \FunctionTok{round}\NormalTok{(}\FunctionTok{prop.table}\NormalTok{(tabla), }\DecValTok{3}\NormalTok{)),}
             \AttributeTok{col.names =} \FunctionTok{c}\NormalTok{(}\StringTok{"Frecuencia"}\NormalTok{, }\StringTok{"Proporción"}\NormalTok{),}
             \AttributeTok{caption =} \StringTok{"Frecuencias del pronóstico al mediodía (n = 118)"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lrr@{}}
\caption{Frecuencias del pronóstico al mediodía (n =
118)}\tabularnewline
\toprule\noalign{}
& Frecuencia & Proporción \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
& Frecuencia & Proporción \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Parcialmente Nublado & 63 & 0.534 \\
Nublado & 31 & 0.263 \\
Parcialmente Nublado - Lluvia Fuerte & 6 & 0.051 \\
Parcialmente Nublado - Llovizna & 5 & 0.042 \\
Nublado - Llovizna & 4 & 0.034 \\
Nublado - Lluvia & 4 & 0.034 \\
Despejado & 3 & 0.025 \\
Parcialmente Nublado - Tormenta Ligera & 2 & 0.017 \\
\end{longtable}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{barplot}\NormalTok{(tabla, }\AttributeTok{horiz =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{las =} \DecValTok{1}\NormalTok{, }\AttributeTok{cex.names =} \FloatTok{0.65}\NormalTok{,}
        \AttributeTok{main =} \StringTok{"Frecuencias del pronóstico al mediodía"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{taller-01_files/figure-latex/frecuencias-1.pdf}}

El pronóstico más frecuente es Parcialmente Nublado (63 de 118, 53.4
\%); el menos frecuente es Parcialmente Nublado - Tormenta Ligera (2).
La distribución concentra la masa en los estados de cielo parcialmente
nublado y nublado, con eventos de lluvia y tormenta poco frecuentes.

\chapter{Clasificación de las variables}\label{p3}

La escala de medición no se deduce del tipo de dato en R: un código
postal es numérico y nominal; los grados centígrados son de intervalo,
no de razón. Escala y clase son dos ejes independientes: cada variable
recibe una de cada eje.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{diccionario }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{columna =} \FunctionTok{c}\NormalTok{(}\StringTok{"Cod\_Div"}\NormalTok{, }\StringTok{"Latitud"}\NormalTok{, }\StringTok{"Longitud"}\NormalTok{, }\StringTok{"Region"}\NormalTok{, }\StringTok{"Departamento"}\NormalTok{,}
              \StringTok{"Municipio"}\NormalTok{, }\StringTok{"Fecha"}\NormalTok{, }\StringTok{"Hora"}\NormalTok{, }\StringTok{"Temperatura"}\NormalTok{,}
              \StringTok{"Velocidad\_del\_Viento"}\NormalTok{, }\StringTok{"Direccion\_del\_Viento"}\NormalTok{, }\StringTok{"Presion"}\NormalTok{,}
              \StringTok{"Punto\_de\_Rocio"}\NormalTok{, }\StringTok{"Cobertura\_total\_nubosa"}\NormalTok{,}
              \StringTok{"Precipitacion\_mm\_h"}\NormalTok{, }\StringTok{"Probabilidad\_de\_Tormenta"}\NormalTok{, }\StringTok{"Humedad"}\NormalTok{,}
              \StringTok{"Pronostico"}\NormalTok{),}
  \AttributeTok{escala =} \FunctionTok{c}\NormalTok{(}\StringTok{"razón"}\NormalTok{, }\StringTok{"razón"}\NormalTok{, }\StringTok{"razón"}\NormalTok{, }\StringTok{"nominal"}\NormalTok{, }\StringTok{"nominal"}\NormalTok{, }\StringTok{"nominal"}\NormalTok{,}
             \StringTok{"nominal"}\NormalTok{, }\StringTok{"nominal"}\NormalTok{, }\StringTok{"intervalo"}\NormalTok{, }\StringTok{"razón"}\NormalTok{, }\StringTok{"razón"}\NormalTok{, }\StringTok{"razón"}\NormalTok{,}
             \StringTok{"razón"}\NormalTok{, }\StringTok{"razón"}\NormalTok{, }\StringTok{"razón"}\NormalTok{, }\StringTok{"razón"}\NormalTok{, }\StringTok{"razón"}\NormalTok{, }\StringTok{"nominal"}\NormalTok{),}
  \AttributeTok{clase =} \FunctionTok{c}\NormalTok{(}\StringTok{"continua"}\NormalTok{, }\StringTok{"continua"}\NormalTok{, }\StringTok{"continua"}\NormalTok{, }\StringTok{"cualitativa"}\NormalTok{, }\StringTok{"cualitativa"}\NormalTok{,}
            \StringTok{"cualitativa"}\NormalTok{, }\StringTok{"cualitativa"}\NormalTok{, }\StringTok{"cualitativa"}\NormalTok{, }\StringTok{"continua"}\NormalTok{,}
            \StringTok{"continua"}\NormalTok{, }\StringTok{"continua"}\NormalTok{, }\StringTok{"continua"}\NormalTok{, }\StringTok{"continua"}\NormalTok{, }\StringTok{"continua"}\NormalTok{,}
            \StringTok{"continua"}\NormalTok{, }\StringTok{"discreta"}\NormalTok{, }\StringTok{"continua"}\NormalTok{, }\StringTok{"cualitativa"}\NormalTok{)}
\NormalTok{)}
\NormalTok{knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{(diccionario,}
             \AttributeTok{caption =} \StringTok{"Diccionario de columnas: escala y clase declaradas"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lll@{}}
\caption{Diccionario de columnas: escala y clase
declaradas}\tabularnewline
\toprule\noalign{}
columna & escala & clase \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
columna & escala & clase \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Cod\_Div & razón & continua \\
Latitud & razón & continua \\
Longitud & razón & continua \\
Region & nominal & cualitativa \\
Departamento & nominal & cualitativa \\
Municipio & nominal & cualitativa \\
Fecha & nominal & cualitativa \\
Hora & nominal & cualitativa \\
Temperatura & intervalo & continua \\
Velocidad\_del\_Viento & razón & continua \\
Direccion\_del\_Viento & razón & continua \\
Presion & razón & continua \\
Punto\_de\_Rocio & razón & continua \\
Cobertura\_total\_nubosa & razón & continua \\
Precipitacion\_mm\_h & razón & continua \\
Probabilidad\_de\_Tormenta & razón & discreta \\
Humedad & razón & continua \\
Pronostico & nominal & cualitativa \\
\end{longtable}

Para las cuatro variables del enunciado:

\begin{itemize}
\tightlist
\item
  \textbf{Pronóstico}: nominal (las 11 categorías combinan dos
  dimensiones ordenadas ---nubosidad y precipitación---, por lo que no
  existe un orden total único) y cualitativa politómica.
\item
  \textbf{Municipio}: nominal y cualitativa politómica.
\item
  \textbf{Temperatura (°C)}: intervalo (intervalos equidistantes pero
  cero relativo: 0 °C no es ausencia de temperatura) y continua.
\item
  \textbf{Velocidad del viento (mph)}: razón (cero absoluto: 0 mph es
  ausencia de viento) y continua.
\end{itemize}

\includegraphics[width=5.2in,height=2.4in]{taller-01_files/figure-latex/mermaid-figure-1.png}

Eje 1 --- escala de medición: niveles acumulativos; cada uno hereda las
propiedades del anterior.

\includegraphics[width=5.2in,height=2.13in]{taller-01_files/figure-latex/mermaid-figure-2.png}

Eje 2 --- clase según el recorrido; es independiente del eje 1: cada
variable recibe una escala y una clase.

\chapter{Diagramas de caja: temperatura y viento}\label{p4}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{boxplot}\NormalTok{(datos}\SpecialCharTok{$}\NormalTok{Temperatura, }\AttributeTok{horizontal =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{main =} \StringTok{"Temperatura (°C)"}\NormalTok{,}
        \AttributeTok{col =} \StringTok{"skyblue"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \pandocbounded{\includegraphics[keepaspectratio]{taller-01_files/figure-latex/boxplot-temp-1.pdf}}

}

\caption{Distribución de la temperatura al mediodía (°C)}

\end{figure}%

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{boxplot}\NormalTok{(datos}\SpecialCharTok{$}\NormalTok{Velocidad\_del\_Viento, }\AttributeTok{horizontal =} \ConstantTok{TRUE}\NormalTok{,}
        \AttributeTok{main =} \StringTok{"Velocidad del viento (mph)"}\NormalTok{, }\AttributeTok{col =} \StringTok{"lightgreen"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \pandocbounded{\includegraphics[keepaspectratio]{taller-01_files/figure-latex/boxplot-viento-1.pdf}}

}

\caption{Distribución de la velocidad del viento al mediodía (mph)}

\end{figure}%

\textbf{Temperatura.} Centro: mediana \(\approx\) 30.4 °C. Localización:
el 50 \% central de los días (Q1 a Q3) vive en una banda estrecha
alrededor de 29--31.5 °C. Dispersión: RIC de \(\approx\) 2.5 °C; bigote
derecho corto (el máximo está a \(\approx\) 1.4 °C de Q3) y bigote
izquierdo largo, señal de asimetría negativa: unos pocos días frescos
estiran la distribución hacia abajo.

\textbf{Velocidad del viento.} Centro: mediana \(\approx\) 1.7 mph.
Dispersión relativa mucho mayor (RIC \(\approx\) 1.2 sobre un nivel de
1.7). El bigote derecho es más largo que el izquierdo: asimetría
positiva, coherente con una variable con piso físico en cero que solo
puede estirarse hacia arriba.

\chapter{Resumen numérico}\label{p5}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x }\OtherTok{\textless{}{-}}\NormalTok{ datos}\SpecialCharTok{$}\NormalTok{Temperatura}
\NormalTok{v }\OtherTok{\textless{}{-}}\NormalTok{ x[}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(x)]}
\NormalTok{centrado }\OtherTok{\textless{}{-}}\NormalTok{ v }\SpecialCharTok{{-}} \FunctionTok{mean}\NormalTok{(v)}
\NormalTok{raiz }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{(}\FunctionTok{mean}\NormalTok{(centrado}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{))}
\NormalTok{asimetria }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(centrado}\SpecialCharTok{\^{}}\DecValTok{3}\NormalTok{) }\SpecialCharTok{/}\NormalTok{ raiz}\SpecialCharTok{\^{}}\DecValTok{3}        \CommentTok{\# g1: hacia dónde va la cola}
\NormalTok{curtosis }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(centrado}\SpecialCharTok{\^{}}\DecValTok{4}\NormalTok{) }\SpecialCharTok{/}\NormalTok{ raiz}\SpecialCharTok{\^{}}\DecValTok{4} \SpecialCharTok{{-}} \DecValTok{3}     \CommentTok{\# g2: exceso sobre la normal}
\NormalTok{knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{(}\FunctionTok{data.frame}\NormalTok{(}
\NormalTok{  estadístico }\OtherTok{=} \FunctionTok{c}\NormalTok{(}\StringTok{"n"}\NormalTok{, }\StringTok{"mínimo"}\NormalTok{, }\StringTok{"Q1"}\NormalTok{, }\StringTok{"mediana"}\NormalTok{, }\StringTok{"media"}\NormalTok{, }\StringTok{"Q3"}\NormalTok{, }\StringTok{"máximo"}\NormalTok{,}
                  \StringTok{"desviación"}\NormalTok{, }\StringTok{"RIC"}\NormalTok{),}
  \AttributeTok{valor =} \FunctionTok{round}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\FunctionTok{length}\NormalTok{(v), }\FunctionTok{min}\NormalTok{(v), }\FunctionTok{quantile}\NormalTok{(v, .}\DecValTok{25}\NormalTok{), }\FunctionTok{median}\NormalTok{(v), }\FunctionTok{mean}\NormalTok{(v),}
                  \FunctionTok{quantile}\NormalTok{(v, .}\DecValTok{75}\NormalTok{), }\FunctionTok{max}\NormalTok{(v), }\FunctionTok{sd}\NormalTok{(v), }\FunctionTok{IQR}\NormalTok{(v)), }\DecValTok{2}\NormalTok{)}
\NormalTok{), }\AttributeTok{caption =} \StringTok{"Resumen de la temperatura al mediodía (°C)"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lr@{}}
\caption{Resumen de la temperatura al mediodía (°C)}\tabularnewline
\toprule\noalign{}
estadístico & valor \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
estadístico & valor \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
n & 118.00 \\
mínimo & 22.40 \\
Q1 & 28.83 \\
mediana & 30.40 \\
media & 29.75 \\
Q3 & 31.30 \\
máximo & 32.70 \\
desviación & 2.28 \\
RIC & 2.47 \\
\end{longtable}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Moda:"}\NormalTok{, }\FunctionTok{names}\NormalTok{(}\FunctionTok{which.max}\NormalTok{(}\FunctionTok{table}\NormalTok{(v))), }\StringTok{"· g1:"}\NormalTok{, }\FunctionTok{round}\NormalTok{(asimetria, }\DecValTok{3}\NormalTok{),}
    \StringTok{"· g2:"}\NormalTok{, }\FunctionTok{round}\NormalTok{(curtosis, }\DecValTok{3}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Moda: 31 · g1: -1.391 · g2: 1.576 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x }\OtherTok{\textless{}{-}}\NormalTok{ datos}\SpecialCharTok{$}\NormalTok{Velocidad\_del\_Viento}
\NormalTok{v }\OtherTok{\textless{}{-}}\NormalTok{ x[}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(x)]}
\NormalTok{centrado }\OtherTok{\textless{}{-}}\NormalTok{ v }\SpecialCharTok{{-}} \FunctionTok{mean}\NormalTok{(v)}
\NormalTok{raiz }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{(}\FunctionTok{mean}\NormalTok{(centrado}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{))}
\NormalTok{asimetria }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(centrado}\SpecialCharTok{\^{}}\DecValTok{3}\NormalTok{) }\SpecialCharTok{/}\NormalTok{ raiz}\SpecialCharTok{\^{}}\DecValTok{3}
\NormalTok{curtosis }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(centrado}\SpecialCharTok{\^{}}\DecValTok{4}\NormalTok{) }\SpecialCharTok{/}\NormalTok{ raiz}\SpecialCharTok{\^{}}\DecValTok{4} \SpecialCharTok{{-}} \DecValTok{3}
\NormalTok{knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{(}\FunctionTok{data.frame}\NormalTok{(}
\NormalTok{  estadístico }\OtherTok{=} \FunctionTok{c}\NormalTok{(}\StringTok{"n"}\NormalTok{, }\StringTok{"mínimo"}\NormalTok{, }\StringTok{"Q1"}\NormalTok{, }\StringTok{"mediana"}\NormalTok{, }\StringTok{"media"}\NormalTok{, }\StringTok{"Q3"}\NormalTok{, }\StringTok{"máximo"}\NormalTok{,}
                  \StringTok{"desviación"}\NormalTok{, }\StringTok{"RIC"}\NormalTok{),}
  \AttributeTok{valor =} \FunctionTok{round}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\FunctionTok{length}\NormalTok{(v), }\FunctionTok{min}\NormalTok{(v), }\FunctionTok{quantile}\NormalTok{(v, .}\DecValTok{25}\NormalTok{), }\FunctionTok{median}\NormalTok{(v), }\FunctionTok{mean}\NormalTok{(v),}
                  \FunctionTok{quantile}\NormalTok{(v, .}\DecValTok{75}\NormalTok{), }\FunctionTok{max}\NormalTok{(v), }\FunctionTok{sd}\NormalTok{(v), }\FunctionTok{IQR}\NormalTok{(v)), }\DecValTok{2}\NormalTok{)}
\NormalTok{), }\AttributeTok{caption =} \StringTok{"Resumen de la velocidad del viento al mediodía (mph)"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lr@{}}
\caption{Resumen de la velocidad del viento al mediodía
(mph)}\tabularnewline
\toprule\noalign{}
estadístico & valor \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
estadístico & valor \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
n & 118.00 \\
mínimo & 0.40 \\
Q1 & 1.00 \\
mediana & 1.70 \\
media & 1.72 \\
Q3 & 2.18 \\
máximo & 3.70 \\
desviación & 0.79 \\
RIC & 1.18 \\
\end{longtable}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Moda:"}\NormalTok{, }\FunctionTok{names}\NormalTok{(}\FunctionTok{which.max}\NormalTok{(}\FunctionTok{table}\NormalTok{(v))), }\StringTok{"· g1:"}\NormalTok{, }\FunctionTok{round}\NormalTok{(asimetria, }\DecValTok{3}\NormalTok{),}
    \StringTok{"· g2:"}\NormalTok{, }\FunctionTok{round}\NormalTok{(curtosis, }\DecValTok{3}\NormalTok{), }\StringTok{"· CV:"}\NormalTok{, }\FunctionTok{round}\NormalTok{(}\FunctionTok{sd}\NormalTok{(v) }\SpecialCharTok{/} \FunctionTok{mean}\NormalTok{(v), }\DecValTok{3}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Moda: 0.9 · g1: 0.485 · g2: -0.323 · CV: 0.459 
\end{verbatim}

\textbf{Concuerda con los boxplots.} En temperatura, media (29.75)
\textless{} mediana (30.4) \textless{} moda (31): la cascada clásica de
la asimetría negativa; el coeficiente de asimetría g1 \(\approx\) -1.4
la confirma. En el viento, media y mediana casi coinciden con g1
\(\approx\) 0.49: asimetría positiva leve. El CV solo se reporta para el
viento (escala razón): 46 \% frente a la estabilidad térmica relativa
del mediodía.

\chapter{Valores atípicos: presión y punto de rocío}\label{p6}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x }\OtherTok{\textless{}{-}}\NormalTok{ datos}\SpecialCharTok{$}\NormalTok{Presion}
\NormalTok{caja }\OtherTok{\textless{}{-}} \FunctionTok{boxplot}\NormalTok{(x, }\AttributeTok{plot =} \ConstantTok{FALSE}\NormalTok{)}
\NormalTok{atipicos }\OtherTok{\textless{}{-}}\NormalTok{ caja}\SpecialCharTok{$}\NormalTok{out}
\NormalTok{ric }\OtherTok{\textless{}{-}} \FunctionTok{diff}\NormalTok{(caja}\SpecialCharTok{$}\NormalTok{stats[}\FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{4}\NormalTok{)])}
\NormalTok{cercas }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(caja}\SpecialCharTok{$}\NormalTok{stats[}\DecValTok{2}\NormalTok{] }\SpecialCharTok{{-}} \FloatTok{1.5} \SpecialCharTok{*}\NormalTok{ ric, caja}\SpecialCharTok{$}\NormalTok{stats[}\DecValTok{4}\NormalTok{] }\SpecialCharTok{+} \FloatTok{1.5} \SpecialCharTok{*}\NormalTok{ ric)}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Presión — atípicos de Tukey:"}\NormalTok{, }\FunctionTok{length}\NormalTok{(atipicos), }\StringTok{"de"}\NormalTok{, }\FunctionTok{length}\NormalTok{(x), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Presión — atípicos de Tukey: 1 de 118 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Cercas:"}\NormalTok{, }\FunctionTok{round}\NormalTok{(cercas, }\DecValTok{2}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Cercas: 1009.65 1015.65 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{round}\NormalTok{(atipicos, }\DecValTok{2}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 1015.7
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{boxplot}\NormalTok{(x, }\AttributeTok{horizontal =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{main =} \StringTok{"Presión (hPa)"}\NormalTok{, }\AttributeTok{col =} \StringTok{"orange"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{taller-01_files/figure-latex/atipicos-presion-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x }\OtherTok{\textless{}{-}}\NormalTok{ datos}\SpecialCharTok{$}\NormalTok{Punto\_de\_Rocio}
\NormalTok{caja }\OtherTok{\textless{}{-}} \FunctionTok{boxplot}\NormalTok{(x, }\AttributeTok{plot =} \ConstantTok{FALSE}\NormalTok{)}
\NormalTok{atipicos }\OtherTok{\textless{}{-}}\NormalTok{ caja}\SpecialCharTok{$}\NormalTok{out}
\NormalTok{ric }\OtherTok{\textless{}{-}} \FunctionTok{diff}\NormalTok{(caja}\SpecialCharTok{$}\NormalTok{stats[}\FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{4}\NormalTok{)])}
\NormalTok{cercas }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(caja}\SpecialCharTok{$}\NormalTok{stats[}\DecValTok{2}\NormalTok{] }\SpecialCharTok{{-}} \FloatTok{1.5} \SpecialCharTok{*}\NormalTok{ ric, caja}\SpecialCharTok{$}\NormalTok{stats[}\DecValTok{4}\NormalTok{] }\SpecialCharTok{+} \FloatTok{1.5} \SpecialCharTok{*}\NormalTok{ ric)}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Punto de rocío — atípicos de Tukey:"}\NormalTok{, }\FunctionTok{length}\NormalTok{(atipicos), }\StringTok{"de"}\NormalTok{,}
    \FunctionTok{length}\NormalTok{(x), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Punto de rocío — atípicos de Tukey: 0 de 118 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Cercas:"}\NormalTok{, }\FunctionTok{round}\NormalTok{(cercas, }\DecValTok{2}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Cercas: 13.35 30.55 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{round}\NormalTok{(atipicos, }\DecValTok{2}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
numeric(0)
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{boxplot}\NormalTok{(x, }\AttributeTok{horizontal =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{main =} \StringTok{"Punto de rocío (°C)"}\NormalTok{, }\AttributeTok{col =} \StringTok{"lightblue"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{taller-01_files/figure-latex/atipicos-rocio-1.pdf}}

El criterio de Tukey (1.5·RIC desde las bisagras) es una convención
geométrica: señala observaciones lejanas del 50 \% central, no errores
de medición. La variable con mayor número de atípicos es la que reporta
la salida; conviene verificar si los extremos de cada variable caen de
un solo lado (firmarían asimetría, no error).

\chapter{Asociación temperatura--viento}\label{p7}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{grafico }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(datos, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Temperatura, }\AttributeTok{y =}\NormalTok{ Velocidad\_del\_Viento)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.6}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method =} \StringTok{"lm"}\NormalTok{, }\AttributeTok{se =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{color =} \StringTok{"firebrick"}\NormalTok{, }\AttributeTok{linetype =} \DecValTok{2}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Temperatura (°C)"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Velocidad del viento (mph)"}\NormalTok{)}
\NormalTok{ggExtra}\SpecialCharTok{::}\FunctionTok{ggMarginal}\NormalTok{(grafico, }\AttributeTok{type =} \StringTok{"histogram"}\NormalTok{, }\AttributeTok{fill =} \StringTok{"grey70"}\NormalTok{,}
                    \AttributeTok{color =} \StringTok{"white"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \pandocbounded{\includegraphics[keepaspectratio]{taller-01_files/figure-latex/dispersion-1.pdf}}

}

\caption{Dispersión de temperatura vs.~velocidad del viento con
histogramas marginales}

\end{figure}%

La nube no muestra una dirección clara: a temperaturas altas el viento
toma casi todo su recorrido y a temperaturas bajas también. La recta
ajustada (aproximación lineal) es casi plana, anticipando una asociación
débil.

\chapter{Covarianza y correlación}\label{p8}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cov\_tv }\OtherTok{\textless{}{-}} \FunctionTok{cov}\NormalTok{(datos}\SpecialCharTok{$}\NormalTok{Temperatura, datos}\SpecialCharTok{$}\NormalTok{Velocidad\_del\_Viento,}
              \AttributeTok{use =} \StringTok{"complete.obs"}\NormalTok{)}
\NormalTok{cor\_tv }\OtherTok{\textless{}{-}} \FunctionTok{cor}\NormalTok{(datos}\SpecialCharTok{$}\NormalTok{Temperatura, datos}\SpecialCharTok{$}\NormalTok{Velocidad\_del\_Viento,}
              \AttributeTok{use =} \StringTok{"complete.obs"}\NormalTok{)}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Covarianza:"}\NormalTok{, }\FunctionTok{round}\NormalTok{(cov\_tv, }\DecValTok{4}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Covarianza: 0.0472 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Pearson:   "}\NormalTok{, }\FunctionTok{round}\NormalTok{(cor\_tv, }\DecValTok{4}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Pearson:    0.0263 
\end{verbatim}

La covarianza vive en unidades de producto (°C·mph) y su magnitud no es
interpretable por sí sola; el coeficiente de Pearson es adimensional y
queda en 0.026. Con \textbar r\textbar{} tan cercano a cero, la
asociación lineal es prácticamente nula: conocer la temperatura del
mediodía no ayuda a predecir el viento (linealmente).

\chapter{Dimensionalidad de los datos}\label{p9}

Los análisis de las secciones anteriores son \textbf{univariados} (una
variable: boxplots, resúmenes, atípicos) y \textbf{bivariados}
(temperatura vs.~viento: dispersión, covarianza, correlación). El
conjunto de datos en sí, con 18 variables medidas por unidad
estadística, es \textbf{multivariado}; los métodos para explotar esa
estructura (por ejemplo, componentes principales) vienen más adelante en
el curso.

\chapter{Estimación de densidades}\label{p10}

\section{Temperatura: histograma y
kernel}\label{temperatura-histograma-y-kernel}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(datos, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Temperatura)) }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =} \FunctionTok{after\_stat}\NormalTok{(density)), }\AttributeTok{bins =} \DecValTok{15}\NormalTok{,}
                 \AttributeTok{fill =} \StringTok{"lightblue"}\NormalTok{, }\AttributeTok{color =} \StringTok{"black"}\NormalTok{, }\AttributeTok{alpha =} \FloatTok{0.6}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_density}\NormalTok{(}\AttributeTok{color =} \StringTok{"darkblue"}\NormalTok{, }\AttributeTok{linewidth =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Temperatura (°C)"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Densidad"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \pandocbounded{\includegraphics[keepaspectratio]{taller-01_files/figure-latex/densidad-temp-1.pdf}}

}

\caption{Temperatura al mediodía: estimación histograma y kernel de la
densidad}

\end{figure}%

La densidad estimada no es compatible con una normal: la masa se apila
contra el techo térmico (montaña a la derecha) y una cola izquierda
larga (g1 \(\approx\) -1.4, g2 \textgreater{} 0). Los días anómalamente
frescos ---coherentes con pronósticos de lluvia--- son más frecuentes de
lo que una campana con esa misma desviación prometería.

\section{Presión: simetría}\label{presiuxf3n-simetruxeda}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(datos, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Presion)) }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =} \FunctionTok{after\_stat}\NormalTok{(density)), }\AttributeTok{bins =} \DecValTok{15}\NormalTok{,}
                 \AttributeTok{fill =} \StringTok{"orange"}\NormalTok{, }\AttributeTok{color =} \StringTok{"black"}\NormalTok{, }\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_density}\NormalTok{(}\AttributeTok{color =} \StringTok{"brown"}\NormalTok{, }\AttributeTok{linewidth =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Presión (hPa)"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Densidad"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \pandocbounded{\includegraphics[keepaspectratio]{taller-01_files/figure-latex/densidad-presion-1.pdf}}

}

\caption{Presión al mediodía: estimación histograma y kernel de la
densidad}

\end{figure}%

\section{Velocidad del viento: KDE vs.~normal
teórica}\label{velocidad-del-viento-kde-vs.-normal-teuxf3rica}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{media\_v }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(datos}\SpecialCharTok{$}\NormalTok{Velocidad\_del\_Viento, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{sd\_v }\OtherTok{\textless{}{-}} \FunctionTok{sd}\NormalTok{(datos}\SpecialCharTok{$}\NormalTok{Velocidad\_del\_Viento, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\FunctionTok{ggplot}\NormalTok{(datos, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Velocidad\_del\_Viento)) }\SpecialCharTok{+}
  \FunctionTok{geom\_density}\NormalTok{(}\AttributeTok{color =} \StringTok{"blue"}\NormalTok{, }\AttributeTok{linewidth =} \FloatTok{1.2}\NormalTok{, }\AttributeTok{fill =} \StringTok{"blue"}\NormalTok{, }\AttributeTok{alpha =} \FloatTok{0.2}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{stat\_function}\NormalTok{(}\AttributeTok{fun =}\NormalTok{ dnorm, }\AttributeTok{args =} \FunctionTok{list}\NormalTok{(}\AttributeTok{mean =}\NormalTok{ media\_v, }\AttributeTok{sd =}\NormalTok{ sd\_v),}
                \AttributeTok{color =} \StringTok{"red"}\NormalTok{, }\AttributeTok{linetype =} \StringTok{"dashed"}\NormalTok{, }\AttributeTok{linewidth =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Velocidad del viento (mph)"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Densidad"}\NormalTok{,}
       \AttributeTok{caption =} \StringTok{"Azul: KDE empírica | Rojo punteado: normal teórica"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \pandocbounded{\includegraphics[keepaspectratio]{taller-01_files/figure-latex/densidad-viento-1.pdf}}

}

\caption{Velocidad del viento: densidad kernel vs.~normal teórica con
media y desviación observadas}

\end{figure}%

El modelo normal ajusta razonablemente el centro de la distribución,
pero subestima la cola derecha (la empírica cae más lento) y sobreestima
la masa cerca de cero. La asimetría positiva leve (g1 \(\approx\) 0.5) y
el piso en cero explican la discrepancia: la normal es una aproximación
aceptable para cálculos gruesos, no un modelo exacto del viento.

% --- Referencias mínimas (fuente de datos + software usado) ---
\nocite{ideam-datos, r-core, ggplot2, ggextra}
\printbibliography[heading=bibintoc]
\end{document}
